"""update_tables

Revision ID: 0e895bac126e
Revises: 0ce698b4a707
Create Date: 2023-04-24 09:39:13.205068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e895bac126e'
down_revision = '0ce698b4a707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_drinks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('cart_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('drink_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_drinks', schema=None) as batch_op:
        batch_op.alter_column('drink_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('cart_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('id')

    # ### end Alembic commands ###