"""create_tables

Revision ID: 1d83a5085bb3
Revises: ffdc0a98111c
Create Date: 2023-04-24 11:38:23.229091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d83a5085bb3'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('subCategory', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('imageUrl', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_paids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drink_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=40), nullable=False),
    sa.Column('milk', sa.String(length=255), nullable=True),
    sa.Column('preparationMethod', sa.String(length=255), nullable=True),
    sa.Column('shotOptions', sa.Integer(), nullable=True),
    sa.Column('expressoRoastOptions', sa.String(length=255), nullable=True),
    sa.Column('teaBase', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['drink_id'], ['drinks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('drink_id', sa.Integer(), nullable=False),
    sa.Column('reviewBody', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drink_id'], ['drinks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_customizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('customization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['customization_id'], ['customizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_drinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('drink_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['drink_id'], ['drinks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordered_drinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cart_paid_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cart_paid_id'], ['cart_paids.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_paid_ordered_drink',
    sa.Column('cart_paid_id', sa.Integer(), nullable=True),
    sa.Column('ordered_drink_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart_paid_id'], ['cart_paids.id'], ),
    sa.ForeignKeyConstraint(['ordered_drink_id'], ['ordered_drinks.id'], )
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funds', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('funds')

    op.drop_table('cart_paid_ordered_drink')
    op.drop_table('ordered_drinks')
    op.drop_table('cart_drinks')
    op.drop_table('cart_customizations')
    op.drop_table('reviews')
    op.drop_table('customizations')
    op.drop_table('carts')
    op.drop_table('cart_paids')
    op.drop_table('drinks')
    # ### end Alembic commands ###