"""create_posts_table

Revision ID: f4515189517b
Revises: 60ee2c15871b
Create Date: 2023-04-26 16:17:42.655828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4515189517b'
down_revision = '60ee2c15871b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(length=250), nullable=False),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=250), nullable=False),
    sa.Column('post_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('posts_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['posts_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('users_id', 'posts_id')
    )
    op.create_table('post_custs',
    sa.Column('posts_id', sa.Integer(), nullable=False),
    sa.Column('customizations_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customizations_id'], ['customizations.id'], ),
    sa.ForeignKeyConstraint(['posts_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('posts_id', 'customizations_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    op.drop_table('post_custs')
    op.drop_table('likes')
    op.drop_table('posts')
    # ### end Alembic commands ###