"""empty message

Revision ID: c623c03bb98d
Revises: 
Create Date: 2023-04-19 10:28:39.317322

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = 'c623c03bb98d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('subCategory', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('funds', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('drink_id', sa.Integer(), nullable=False),
    sa.Column('reviewBody', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drink_id'], ['drinks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_drink',
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('drink_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['drink_id'], ['drinks.id'], ),
    sa.PrimaryKeyConstraint('cart_id', 'drink_id')
    )
    op.create_table('customizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('drink_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=40), nullable=False),
    sa.Column('milk', sa.String(length=255), nullable=False),
    sa.Column('preparationMethod', sa.String(length=255), nullable=False),
    sa.Column('shotOptions', sa.Integer(), nullable=True),
    sa.Column('expressoRoastOptions', sa.String(length=255), nullable=True),
    sa.Column('teaBase', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['drink_id'], ['drinks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('addIns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customization_id', sa.Integer(), nullable=False),
    sa.Column('chocolateMaltPowder', sa.String(length=255), nullable=True),
    sa.Column('vanillaBeanPowder', sa.Integer(), nullable=True),
    sa.Column('ice', sa.String(length=255), nullable=True),
    sa.Column('lineTheCup', sa.String(length=255), nullable=True),
    sa.Column('room', sa.String(length=255), nullable=True),
    sa.Column('creamer', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['customization_id'], ['customizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flavors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customization_id', sa.Integer(), nullable=False),
    sa.Column('brownSugarSyrup', sa.Integer(), nullable=True),
    sa.Column('caramelSyrup', sa.Integer(), nullable=True),
    sa.Column('cinnamonDolceSyrup', sa.Integer(), nullable=True),
    sa.Column('hazelnulSyrup', sa.Integer(), nullable=True),
    sa.Column('peppermintSyrup', sa.Integer(), nullable=True),
    sa.Column('raspberrySyrup', sa.Integer(), nullable=True),
    sa.Column('toastedVanillaSyrup', sa.Integer(), nullable=True),
    sa.Column('toffeenutSyrup', sa.Integer(), nullable=True),
    sa.Column('vanillaSyrup', sa.Integer(), nullable=True),
    sa.Column('sugarFreeVanillaSyrup', sa.Integer(), nullable=True),
    sa.Column('mochaSauce', sa.Integer(), nullable=True),
    sa.Column('newDarkCaramelSauce', sa.Integer(), nullable=True),
    sa.Column('pistachioSauce', sa.Integer(), nullable=True),
    sa.Column('whiteChocolateMochaSauce', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customization_id'], ['customizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sweeteners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customization_id', sa.Integer(), nullable=False),
    sa.Column('sugar', sa.Integer(), nullable=True),
    sa.Column('sugarInTheRaw', sa.Integer(), nullable=True),
    sa.Column('honey', sa.Integer(), nullable=True),
    sa.Column('splenda', sa.Integer(), nullable=True),
    sa.Column('steviaInTheRaw', sa.Integer(), nullable=True),
    sa.Column('classicSyrup', sa.Integer(), nullable=True),
    sa.Column('liquidCaneSugar', sa.Integer(), nullable=True),
    sa.Column('honeyBlend', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customization_id'], ['customizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toppings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customization_id', sa.Integer(), nullable=False),
    sa.Column('caramelCrunchTopping', sa.String(length=255), nullable=True),
    sa.Column('cookieCrumbleTopping', sa.String(length=255), nullable=True),
    sa.Column('saltedBrownButterTopping', sa.String(length=255), nullable=True),
    sa.Column('cinnamonDolceSprinkles', sa.String(length=255), nullable=True),
    sa.Column('caramelDrizzle', sa.String(length=255), nullable=True),
    sa.Column('mochaDrizzle', sa.String(length=255), nullable=True),
    sa.Column('chocolateCreamColdFoam', sa.String(length=255), nullable=True),
    sa.Column('cinnamonSweetCreamColdFoam', sa.String(length=255), nullable=True),
    sa.Column('pistachioCreamColdFoam', sa.String(length=255), nullable=True),
    sa.Column('saltedCaramelCreamColdFoam', sa.String(length=255), nullable=True),
    sa.Column('vanillaSweetCreamColdFoam', sa.String(length=255), nullable=True),
    sa.Column('cinnamonPowder', sa.String(length=255), nullable=True),
    sa.Column('whippedCream', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['customization_id'], ['customizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toppings')
    op.drop_table('sweeteners')
    op.drop_table('flavors')
    op.drop_table('addIns')
    op.drop_table('customizations')
    op.drop_table('cart_drink')
    op.drop_table('reviews')
    op.drop_table('carts')
    op.drop_table('users')
    op.drop_table('drinks')
    # ### end Alembic commands ###