"""update_tables

Revision ID: 8d6f30bcc2b5
Revises: 1d83a5085bb3
Create Date: 2023-04-25 11:58:23.697894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d6f30bcc2b5'
down_revision = '1d83a5085bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_paids')
    op.drop_table('cart_paid_ordered_drink')
    op.drop_table('ordered_drinks')
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('created_time', sa.DateTime, nullable=True))
        batch_op.add_column(sa.Column('paid_time', sa.DateTime, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_column('paid_time')
        batch_op.drop_column('created_time')
        batch_op.drop_column('paid')

    op.create_table('ordered_drinks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('cart_paid_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['cart_paid_id'], ['cart_paids.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_paid_ordered_drink',
    sa.Column('cart_paid_id', sa.INTEGER(), nullable=True),
    sa.Column('ordered_drink_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['cart_paid_id'], ['cart_paids.id'], ),
    sa.ForeignKeyConstraint(['ordered_drink_id'], ['ordered_drinks.id'], )
    )
    op.create_table('cart_paids',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('total_price', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###