"""update_customizations_table

Revision ID: 8b4083966a1a
Revises: 89c7864e1174
Create Date: 2023-04-30 10:14:09.745740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b4083966a1a'
down_revision = '89c7864e1174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('toppings', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('flavors', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('addIns', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sweeteners', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customizations', schema=None) as batch_op:
        batch_op.drop_column('sweeteners')
        batch_op.drop_column('addIns')
        batch_op.drop_column('flavors')
        batch_op.drop_column('toppings')

    # ### end Alembic commands ###